### ISSUE TITLE
Does it c99 support?

### ISSUE THREAD

**Issue by DeanHH** [emcrisostomo/fswatch#128] opened 2016-07-19 07:31 UTC
Problem happend when I try to build my c99 project with fswatch.The `#include <ctime>` is not found.

**Comment by emcrisostomo** [comment] 2016-07-23 16:17
That's a known bug: C files are sometimes using C++ header names and that result in a build failure when using a C compiler.  That's being worked on `1.9.3`.

Closed as duplicate of #120.

**Closed by emcrisostomo** 2016-07-23 16:17 UTC
