### ISSUE TITLE
Statically linked (Linux ARM musl) does not work after refactoring

### ISSUE THREAD

**Issue by jsarenik** [emcrisostomo/fswatch#173] opened 2017-08-16 16:04 UTC
Hi @emcrisostomo!

I am using `fswatch` on ARM Linux, statically linked against musl libc. Version 1.7.0 works well but master (529c7e8) does not so I did following bisect script to find out what commit broke my use-case (compiling on Arch Linux x86_64, gcc 7.1.1, autoconf 2.69):

```
#!/bin/sh
#
# Download toolchain armv7-eabihf--musl--stable-2017.05-toolchains-1-1.tar.bz2
# from http://toolchains.free-electrons.com/ and extract it (into /path/to)
# http://toolchains.free-electrons.com/downloads/releases/toolchains/armv7-eabihf/tarballs/armv7-eabihf--musl--stable-2017.05-toolchains-1-1.tar.bz2

git reset --hard
git clean -xfd
./autogen.sh
export PATH=/path/to/armv7-eabihf--musl--stable/bin:$PATH                  
./configure --host=arm-buildroot-linux-musleabihf LDFLAGS="-static"
make -j$(grep -c ^processor /proc/cpuinfo)
find . -perm -700 -name fswatch | xargs strings | grep -w inotify_monitor
```

Partial log of my bisect run:

```
$ git bisect start
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git bisect bad
$ git bisect good 1.7.0
Bisecting: 143 revisions left to test after this (roughly 7 steps)
[1bd5bbad48903453c78036b1e9d1c42f72783c25] Add check for the availability of std::atomic.
$ git bisect run ~/bisect-run-fswatch.sh
...
0c3e4e9485594401434346ce1d40072683504c3e is the first bad commit
commit 0c3e4e9485594401434346ce1d40072683504c3e
Author: Enrico M. Crisostomo <enrico.m.crisostomo@gmail.com>
Date:   Wed Dec 16 11:22:17 2015 +0100

    Refactory monitor_factory to dynamically create the default monitor using the factory registration info.

:040000 040000 d5a4d8977389ebdb5bb7e0505161feec9f98d84a 2db544c8aa36afb3d22482b9045a07852381d107 M	libfswatch
bisect run success
```

Excuse me for not having enough time to dig deeper :-)
Let me know if I can provide any more details.

`fswatch` is a great tool! Thank you!!!

**Comment by emcrisostomo** [comment] 2018-09-25 15:40
Closing as duplicate of #142

**Closed by emcrisostomo** 2018-09-25 15:40 UTC
